#!/bin/sh




if grep -qv noswap /proc/cmdline; then
  echo "LOAD SWAP"
  for ONESWAP in `fdisk -l | grep ' Linux swap' | cut -f 1 -d ' ' | tr '\n' ' '`
  do
    echo -n "Loading swap partition $ONESWAP..." >/dev/console
    swapon $ONESWAP

    [ $? -eq 0 ] && SWAPON="yes"
  done
fi



if [ -f /mnt/live/tmp/changes-exit ]; then
hdrv=`cat /mnt/live/etc/homedrv | cut -c6-9`
if grep -q noauto /proc/cmdline; then
mkdir -p /mnt/live/mnt/$hdrv 2> /dev/null
mount /dev/$hdrv /mnt/live/mnt/$hdrv 2> /dev/null
ln -snf /mnt/live/mnt/$hdrv /mnt/home
else
ln -snf /mnt/$hdrv /mnt/home
fi
else
hdrv=`cat /mnt/live/etc/homedrv | cut -c6-9`
if [ ! -d /mnt/$hdrv ]; then
mkdir /mnt/$hdrv
fi
mount /dev/$hdrv /mnt/$hdrv

ln -snf /mnt/$hdrv /mnt/home
 fi
(if [ -f /mnt/live/tmp/changes-exit ]; then ln -snf /mnt/live/memory/images/changes-exit /mnt/saved; else ln -snf /mnt/live/memory/changes /mnt/saved; fi) &
exit 0
