#!/bin/bash

MOD_FILE=$1
dn=`basename ${MOD_FILE}`

if [ -d /mnt/live/memory/images/${dn} ]; then
    if [ -f /mnt/live/memory/images/${dn}/stop-mod.sh ]; then
        /mnt/live/memory/images/${dn}/stop-mod.sh
    fi
    umount -l /mnt/live/memory/images/${dn}
fi

losetup -a | grep "${MOD_FILE}" | awk '{print $1}' | cut -f1 -d: | while read loop_dev; do
	losetup -d $loop_dev
done
