#!/bin/bash

MOD_FILE=$1
dn=`basename ${MOD_FILE}`

if [ -d /mnt/live/memory/images/${dn} ]; then
    if [ -f /mnt/live/memory/images/${dn}/stop-mod.sh ]; then
        /mnt/live/memory/images/${dn}/stop-mod.sh
    fi
    umount -l /mnt/live/memory/images/${dn}
fi
